# Configuracion de base de datos para el perfil MySQL (Docker)
spring.datasource.url=jdbc:mysql://localhost:3306/futmanager?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=futuser
spring.datasource.password=futpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
